version: '3.7'

networks:
  api-mongo:
    driver: bridge

services:
  app:
    build: .
    entrypoint: sh ./.docker/entrypoint.sh
    container_name: app-teste
    ports:
      - 3000:3000
      - 3001:3001
    restart: always
    tty: true
    # networks:
    #   - api-mongo
    #   # - front
    volumes:
      - ./:/home/app
    