version: '3.7'

services:
  app:
    build: .
    entrypoint: sh ./.docker/entrypoint.sh
    container_name: app-teste
    ports:
      - 3000:3000
      - 3001:3001
    restart: always
    tty: true
    networks:
      - api-teste
    volumes:
      - ./:/home/app
  db:
    container_name: api-mongo
    image: mongo
    ports:
      - 30000:30000
    restart: always
    tty: true
    environment:
      MONGO_INITDB_ROOT_USERNAME: juliana
      MONGO_INITDB_ROOT_PASSWORD: root1
      # MONGO_INITDB_DATABASE: admin

    networks:
      - api-teste
      
networks:
  api-teste:
    driver: bridge