version: '3.7'

services:
  app:
    build: .
    entrypoint: sh ./.docker/entrypoint.sh
    container_name: app-teste
    ports:
      - 3000:3000
      - 3001:3001
    restart: always
    tty: true
    networks:
      - api-mongo
    volumes:
      - ./:/home/app
  db:
    container_name: api-mongo
    image: mongo
    ports:
      - 30000:30000
    restart: always
    tty: true
    environment:
      MONGO_USER: juliana
      MONGO_PASSWORD: root1
    networks:
      - api-mongo
      
networks:
  api-mongo:
    driver: bridge